name: Create Google Doc on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create-google-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Create Google Doc
      id: create_doc
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_URL="${{ github.event.issue.html_url }}"
        RESPONSE=$(curl -Ls -X POST -d "issueTitle=$ISSUE_TITLE&issueUrl=$ISSUE_URL" 'https://script.google.com/macros/s/AKfycbyot8jOXg8uO0S9-XC_9Hv-GeAY9RxAxCAnWJSkIAcG-ts7dqnVBmTNwQHL0jzVWITh/exec')
        echo "doc_url=$(echo $RESPONSE)" >> $GITHUB_ENV

    - name: Add comment with Google Doc link
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.MY_API_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: "A Google Doc has been created for this issue: ${{ env.doc_url }}"
